; Script generated by the Inno Setup Script Wizard.
; SEE THE DOCUMENTATION FOR DETAILS ON CREATING INNO SETUP SCRIPT FILES!

#define MyAppName "IMS Control Aire v1"
#define MyAppVerName "IMS Control Aire v1"
#define MyAppPublisher "IMS PESAJE"
#define MyAppExeName "imsControlAire.exe"
#define MyAppCarpeta "imsControlAire_SQL"
#define SourceFileDir "D:\Trabajos\Proyectos\imsprogramasC#\09) IMS Control Aire Comprimido"
#define IncludeFramework false
#define IsExternal ""

[Setup]
AppName={#MyAppName}
AppVerName={#MyAppVerName}
AppPublisher={#MyAppPublisher}
DefaultDirName={sd}\{#MyAppCarpeta}
DefaultGroupName=IMS Control Aire
Compression=lzma
SolidCompression=true
ShowLanguageDialog=yes
OutputDir=D:\Trabajos\Proyectos\imsprogramasC#\09) IMS Control Aire Comprimido\imsControlAire\Instalacion
SourceDir=D:\Trabajos\Proyectos\imsprogramasC#\09) IMS Control Aire Comprimido\imsControlAire\Instalacion
UpdateUninstallLogAppName=true
VersionInfoVersion=2.0.0.1
VersionInfoCompany=IMS PESAJE
VersionInfoDescription=imsControlAire
#if IncludeFramework
OutputBaseFilename=Instalar_imsControlAire_SQL_2.0.0.1_FW
#else
OutputBaseFilename=Instalar_imsControlAire_SQL_2.0.0.1
#endif

[Languages]
Name: spa; MessagesFile: compiler:Languages\Spanish.isl

[Tasks]
Name: desktopicon; Description: {cm:CreateDesktopIcon}; GroupDescription: {cm:AdditionalIcons}; Flags: unchecked

[Files]
Source: "D:\Trabajos\Proyectos\imsprogramasC#\09) IMS Control Aire Comprimido\imsControlAire\imsControlAire.exe"; DestDir: "{app}"; Flags: ignoreversion; Languages: spa
; NOTE: Don't use "Flags: ignoreversion" on any shared system files
Source: "D:\Trabajos\Proyectos\imsprogramasC#\09) IMS Control Aire Comprimido\imsControlAire\DevComponents.DotNetBar.Keyboard.dll"; DestDir: "{app}"
Source: "D:\Trabajos\Proyectos\imsprogramasC#\09) IMS Control Aire Comprimido\imsControlAire\ComunicaDll.dll"; DestDir: "{app}"
Source: "D:\Trabajos\Proyectos\imsprogramasC#\09) IMS Control Aire Comprimido\imsControlAire\EPPlus.dll"; DestDir: "{app}"
Source: "D:\Trabajos\Proyectos\imsprogramasC#\09) IMS Control Aire Comprimido\imsControlAire\Funciones.dll"; DestDir: "{app}"
Source: "D:\Trabajos\Proyectos\imsprogramasC#\09) IMS Control Aire Comprimido\imsControlAire\ControlesLib.dll"; DestDir: "{app}"
Source: "D:\Trabajos\Proyectos\imsprogramasC#\09) IMS Control Aire Comprimido\imsControlAire\lectorRFID.dll"; DestDir: "{app}"
Source: "D:\Trabajos\Proyectos\imsprogramasC#\09) IMS Control Aire Comprimido\imsControlAire\RFID.dll"; DestDir: "{app}"
Source: "D:\Trabajos\Proyectos\imsprogramasC#\09) IMS Control Aire Comprimido\imsControlAire\Guna.UI.dll"; DestDir: "{app}"
Source: "D:\Trabajos\Proyectos\imsprogramasC#\09) IMS Control Aire Comprimido\imsControlAire\ComponentFactory.Krypton.Navigator.DLL"; DestDir: "{app}"
Source: "D:\Trabajos\Proyectos\imsprogramasC#\09) IMS Control Aire Comprimido\imsControlAire\ComponentFactory.Krypton.Toolkit.DLL"; DestDir: "{app}"
Source: "D:\Trabajos\Proyectos\imsprogramasC#\09) IMS Control Aire Comprimido\imsControlAire\ControlesLib.dll"; DestDir: "{app}"
Source: "D:\Trabajos\Proyectos\imsprogramasC#\09) IMS Control Aire Comprimido\imsControlAire\KNet.dll"; DestDir: "{app}"
Source: "D:\Trabajos\Proyectos\imsprogramasC#\09) IMS Control Aire Comprimido\imsControlAire\Gestion.ini"; DestDir: "{app}"
; NOTE: Don't use "Flags: ignoreversion" on any shared system files
#if IncludeFramework
Source: "{#SourceFileDir}\dotnetfx35.exe"; DestDir: "{tmp}"; Flags: ignoreversion {#IsExternal}; Check: NeedsFramework
#endif

[Icons]
Name: {group}\{#MyAppCarpeta}; Filename: {app}\imsControlAire.exe
Name: {group}\{cm:UninstallProgram,{#MyAppCarpeta}}; Filename: {uninstallexe}
Name: {userdesktop}\IMS ControlAire v2; Filename: {app}\imsControlAire.exe; Tasks: desktopicon
Name: {commonstartup}\Administrador BD; Filename: {sd}\mysql\bin\winmysqladmin.exe; IconFilename: {sd}\mysql\data\mysql\winmysqladmin.exe; Components: servidor Cliente; Tasks: ; Languages: spa; Check: Check_MySQL

[Run]
Filename: {app}\mysql-connector-odbc-3.51.30-win32.msi; WorkingDir: {app}; Components: servidor; Languages: spa; Flags: nowait skipifsilent; Check: Check_MySQL
Filename: {sd}\mysql\bin\winmysqladmin.exe; WorkingDir: {sd}\mysql\bin; Components: servidor; Languages: spa; Flags: nowait skipifsilent; Check: Check_MySQL
#if IncludeFramework
Filename: {tmp}\dotnetfx35.exe; Parameters: "/q:a /c:""install /l /q"""; WorkingDir: {tmp}; Flags: skipifdoesntexist; StatusMsg: Installing .NET Framework if needed
#endif
Filename: {win}\Microsoft.NET\Framework\v2.0.50727\CasPol.exe; Parameters: "-q -machine -remgroup ""MyApp"""; WorkingDir: {tmp}; Flags: skipifdoesntexist runhidden; StatusMsg: Setting Program Access Permissions...
Filename: {win}\Microsoft.NET\Framework\v2.0.50727\CasPol.exe; Parameters: "-q -machine -addgroup 1.2 -url ""file://{app}/*"" FullTrust -name ""MyApp"""; WorkingDir: {tmp}; Flags: skipifdoesntexist runhidden; StatusMsg: Setting Program Access Permissions...

[UninstallRun]
Filename: {win}\Microsoft.NET\Framework\v2.0.50727\CasPol.exe; Parameters: "-q -machine -remgroup ""MyApp"""; Flags: skipifdoesntexist

[Components]
Name: Servidor; Description: Instalación para Servidor; Languages: spa; Types: T_Servidor
Name: Cliente; Description: Instalación para Clientes; Languages: spa; Types: T_Cliente

[Types]
Name: T_Servidor; Description: Instalación para Servidores; Flags: iscustom
Name: T_Cliente; Description: Instalación Equipos Clientes

[ThirdParty]
CompileLogMethod=append

[Code]
// Página Selección Tipo Base de Datos
var
  //PaginaBD : TWizardPage;
  PaginaBD: TInputOptionWizardPage;
  SQLServer : Boolean;
  SQLite : Boolean;
  MySQL40 : Boolean;

procedure InitializeWizard;
begin
  PaginaBD := CreateInputOptionPage(wpSelectDir,'Selección Base de Datos', 'Seleccione Base de Datos a utilizar', '', True, False);

  //Crea los radio buttons en esta página
  PaginaBD.Add('SQL Server 2008R2');
  PaginaBD.Add('SQLite');
  PaginaBD.Add('MySQL 4.0'); 

  // Selecciona Valores Iniciales
  PaginaBD.Values[0] := False;
end; 

function Check_SQL_Server: Boolean;
begin
  // here write a condition, which if you return True will process an entry;
  // in this example the setup creates the icon if the first radio button is
  // selected
  Result := PaginaBD.Values[0];
end;

function Check_SQLite: Boolean;
begin
  // here write a condition, which if you return True will process an entry;
  // in this example the setup creates the icon if the first radio button is
  // selected
  Result := PaginaBD.Values[1];
end;

function Check_MySQL: Boolean;
begin
  // here write a condition, which if you return True will process an entry;
  // in this example the setup creates the icon if the first radio button is
  // selected
  Result := PaginaBD.Values[2];
end;

// Verifica si S.O. de 32bits
function EsWindows32(): boolean;
begin
  if IsWin64 then
    Result := False
  else
    Result := True;
end;

// Verifica si S.O. de 64bits
function EsWindows64(): boolean;
begin
  if IsWin64 then
    Result := True
  else
    Result := False;
end;

// Indica si .NET Framework 2.0 está instalado.
function IsDotNET20Detected(): boolean;
var
  success: boolean;
  install: cardinal;
begin
  success := RegQueryDWordValue(HKLM, 'SOFTWARE\Microsoft\NET Framework Setup\NDP\v2.0.50727', 'Install', install);
  Result := success and (install = 1);
end;

//RETURNS OPPOSITE OF IsDotNet20Detected FUNCTION
//Remember this method from the Files section above
function NeedsFramework(): Boolean;
begin
  Result := (IsDotNET20Detected = false);
end;

//CHECKS TO SEE IF CLIENT MACHINE IS WINDOWS 95
function IsWin95 : boolean;
begin
  Result := (InstallOnThisVersion('4.0,0', '4.1.1998,0') = irInstall);
end;

//CHECKS TO SEE IF CLIENT MACHINE IS WINDOWS NT4
function IsWinNT : boolean;
begin
  Result := (InstallOnThisVersion('0,4.0.1381', '0,4.0.1381') = irInstall);
end;

//GETS VERSION OF IE INSTALLED ON CLIENT MACHINE
function GetIEVersion : String;
var
  IE_VER: String;
begin
  {First check if Internet Explorer is installed}
  if RegQueryStringValue(HKLM,'SOFTWARE\Microsoft\Internet Explorer','Version',IE_VER) then
      Result := IE_VER
else
    {No Internet Explorer at all}
    result := '';
end;

//GETS THE VERSION OF WINDOWS INSTALLER DLL
function GetMSIVersion(): String;
begin
    GetVersionNumbersString(GetSystemDir+'\msi.dll', Result);
end;

//LAUNCH DEFAULT BROWSER TO WINDOWS UPDATE WEBSITE
procedure GoToWindowsUpdate;
var
  ErrorCode: Integer;
begin
  if (MsgBox('Would you like to go to the Windows Update site now?' + chr(13) + chr(13) + '(Requires Internet Connection)'
            , mbConfirmation, MB_YESNO) = IDYES) then
      ShellExec('open', 'http://windowsupdate.microsoft.com','', '', SW_SHOW, ewNoWait, ErrorCode);
end;
//IF SETUP FINISHES WITH EXIT CODE OF 0, MEANING ALL WENT WELL
//THEN CHECK FOR THE PRESENCE OF THE REGISTRY FLAG TO INDICATE THE
//.NET FRAMEWORK WAS INSTALLED CORRECTLY
//IT CAN FAIL WHEN CUST DOESN'T HAVE CORRECT WINDOWS INSTALLER VERSION
function GetCustomSetupExitCode(): Integer;
begin
  if (IsDotNET20Detected = false) then
    begin
      MsgBox('.NET Framework was NOT installed successfully!',mbError, MB_OK);
      result := -1
    end
end;

function InitializeSetup: Boolean;
var
  Version: TWindowsVersion;
  IE_VER: String;
  MSI_VER: String;
  NL: Char;
  NL2: String;
begin

  NL := Chr(13);
  NL2 := NL + NL;

  // Get Version of Windows from API Call
  GetWindowsVersionEx(Version);

  // On Windows 2000, check for SP3

  if Version.NTPlatform and
     (Version.Major = 5) and
     (Version.Minor = 0) and
     (Version.ServicePackMajor < 3) then
  begin
    SuppressibleMsgBox('When running on Windows 2000, Service Pack 3 is required.' + NL +
                       'Visit' + NL2 +
                       ' *** http://windowsupdate.microsoft.com ***' + NL2 +
                       'to get the needed Windows Updates,' + NL +
                       'and then reinstall this program',
                        mbCriticalError, MB_OK, MB_OK);
    GoToWindowsUpdate;
    Result := False;
    Exit;
  end;

  // On Windows XP, check for SP2
  if Version.NTPlatform and
     (Version.Major = 5) and
     (Version.Minor = 1) and
     (Version.ServicePackMajor < 2) then
  begin
    SuppressibleMsgBox('When running on Windows XP, Service Pack 2 is required.' + NL +
                       'Visit' + NL2 + ' *** http://windowsupdate.microsoft.com ***' + NL2 +
                       'to get the needed Windows Updates,' + NL +
                       'and then reinstall this program',
                       mbCriticalError, MB_OK, MB_OK);
    GoToWindowsUpdate;
    Result := False;
    Exit;
  end;

  //IF WINDOWS 95 OR NT DON'T INSTALL
  if (IsWin95) or (IsWinNT) then
  begin
    SuppressibleMsgBox('This program can not run on Windows 95 or Windows NT.',
      mbCriticalError, MB_OK, MB_OK);
    Result := False;
    Exit;
  end;

  //CHECK MSI VER, NEEDS TO BE 3.0 ON ALL SUPPORTED SYSTEM EXCEPT 95/ME, WHICH NEEDS 2.0)
  MSI_VER := GetMSIVersion
  if ((Version.NTPlatform) and (MSI_VER < '3')) or ((Not Version.NTPlatform) and (MSI_VER < '2')) then
    begin
      SuppressibleMsgBox('You do not have all the required Windows Updates to install this program.' + NL +
                         'Visit *** http://windowsupdate.microsoft.com *** to get the needed Windows Updates,' + NL +
                         'and then reinstall this program',
                         mbCriticalError, MB_OK, MB_OK);
      GoToWindowsUpdate;
      Result := False;
      Exit;
  end;

  //CHECK THE IE VERSION (NEEDS TO BE 5.01+)
  IE_VER := GetIEVersion;
  if IE_VER < '5.01' then
    begin
      if IE_VER = '' then
        begin
          MsgBox('Microsoft Internet Explorer 5.01 or higher is required to run this program.' + NL2 +
                 'You do not currently have Microsoft Internet Explorer installed, or it is not working correctly.' + NL +
                 'Obtain a newer version at www.microsoft.com and then run setup again.', mbInformation, MB_OK);
        end
      else
        begin
          MsgBox('Microsoft Internet Explorer 5.01 or higher is required to run this program.' + NL2 +
                 'You are using version ' + IE_VER + '.' + NL2 +
                 'Obtain a newer version at www.microsoft.com and then run setup again.', mbInformation, MB_OK);
        end;

      GoToWindowsUpdate;
      result := false;
      exit;
  end;

  //MAKE SURE USER HAS ADMIN RIGHTS BEFORE INSTALLING
  if IsAdminLoggedOn then
    begin
      result := true
        exit;
    end
  else
    begin
      MsgBox('You must have admin rights to perform this installation.' + NL +
             'Please log on with an account that has administrative rights,' + NL +
            'and run this installation again.', mbInformation, MB_OK);
        result := false;
    end
  end;
end.

[_ISTool]
UseAbsolutePaths=true

[Registry]
;Root: "HKLM"; Subkey: "SOFTWARE\ODBC\ODBCINST.INI"; ValueType: none; ValueName: "MySQL ODBC 3.51 Driver"; Flags: createvalueifdoesntexist
;Root: "HKLM"; Subkey: "SOFTWARE\ODBC\ODBCINST.INI\MySQL ODBC 3.51 Driver"; ValueType: string; ValueName: "Driver"; ValueData: "{sys}\myodbc3.dll"; Flags: createvalueifdoesntexist
;Root: "HKLM"; Subkey: "SOFTWARE\ODBC\ODBCINST.INI\MySQL ODBC 3.51 Driver"; ValueType: string; ValueName: "Setup"; ValueData: "{sys}\myodbc3S.dll"; Flags: createvalueifdoesntexist
;Root: "HKLM"; Subkey: "SOFTWARE\ODBC\ODBCINST.INI\MySQL ODBC 3.51 Driver"; ValueType: dword; ValueName: "UsageCount"; ValueData: "1"; Flags: createvalueifdoesntexist
;Root: "HKLM"; Subkey: "SOFTWARE\ODBC\ODBCINST.INI\ODBC Drivers"; ValueType: string; ValueName: "MySQL ODBC 3.51 Driver"; ValueData: "Installed"; Flags: createvalueifdoesntexist
; ODBC SQLite - 32 Bits
Root: "HKLM"; Subkey: "SOFTWARE\ODBC\ODBCINST.INI"; ValueType: none; ValueName: "SQLite3 ODBC Driver"; Flags: createvalueifdoesntexist; Components: Cliente Servidor; Languages: spa; Check: EsWindows32
Root: "HKLM"; Subkey: "SOFTWARE\ODBC\ODBCINST.INI\SQLite3 ODBC  Driver"; ValueType: string; ValueName: "Driver"; ValueData: "{sys}\sqlite3odbc.dll"; Flags: createvalueifdoesntexist; Check: EsWindows32
Root: "HKLM"; Subkey: "SOFTWARE\ODBC\ODBCINST.INI\SQLite3 ODBC  Driver"; ValueType: string; ValueName: "Setup"; ValueData: "{sys}\sqlite3odbc.dll"; Flags: createvalueifdoesntexist; Check: EsWindows32
Root: "HKLM"; Subkey: "SOFTWARE\ODBC\ODBCINST.INI\SQLite3 ODBC  Driver"; ValueType: dword; ValueName: "UsageCount"; ValueData: "1"; Flags: createvalueifdoesntexist; Check: EsWindows32
Root: "HKLM"; Subkey: "SOFTWARE\ODBC\ODBCINST.INI\ODBC Drivers"; ValueType: string; ValueName: "SQLite3 ODBC Driver"; ValueData: "Installed"; Flags: createvalueifdoesntexist; Check: EsWindows32
; ODBC SQLite - 64 Bits
Root: "HKLM"; Subkey: "SOFTWARE\Wow6432Node\ODBC\ODBCINST.INI"; ValueType: none; ValueName: "SQLite3 ODBC Driver"; Flags: createvalueifdoesntexist; Components: Cliente Servidor; Languages: spa; Check: EsWindows64
Root: "HKLM"; Subkey: "SOFTWARE\Wow6432Node\ODBC\ODBCINST.INI\SQLite3 ODBC Driver"; ValueType: string; ValueName: "Driver"; ValueData: "{sys}\sqlite3odbc.dll"; Flags: createvalueifdoesntexist; Check: EsWindows64
Root: "HKLM"; Subkey: "SOFTWARE\Wow6432Node\ODBC\ODBCINST.INI\SQLite3 ODBC Driver"; ValueType: string; ValueName: "Setup"; ValueData: "{sys}\sqlite3odbc.dll"; Flags: createvalueifdoesntexist; Check: EsWindows64
Root: "HKLM"; Subkey: "SOFTWARE\Wow6432Node\ODBC\ODBCINST.INI\SQLite3 ODBC Driver"; ValueType: dword; ValueName: "UsageCount"; ValueData: "1"; Flags: createvalueifdoesntexist; Check: EsWindows64
Root: "HKLM"; Subkey: "SOFTWARE\Wow6432Node\ODBC\ODBCINST.INI\ODBC Drivers"; ValueType: string; ValueName: "SQLite3 ODBC Driver"; ValueData: "Installed"; Flags: createvalueifdoesntexist; Check: EsWindows64

[InnoIDE_Settings]
LogFileOverwrite=false

